apiVersion: v1
kind: ConfigMap
metadata:
  name: stackimpl-configmap
  namespace: default
data:
  application.properties: |-
    management.endpoints.web.exposure.include=*
    spring.main.banner-mode=off
    server.port=2021
    spring.jpa.hibernate.ddl-auto=create   
    spring.datasource.url=jdbc:mysql://localhost:3306/mydb
    spring.datasource.username=root
    spring.datasource.password=root
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect